// Atomic Design (Page): Main structure that wires organisms together and
// handles dependency injection and the global or view state.
//
// The learning path: the tree of sequential topics of the chosen track. It is
// what closes AC 1.3 of Story 1.1 —"once the path is defined, the tree of
// sequential topics is shown"—, and that is why it is where the user lands
// after finishing the onboarding.
//
// AI-First: Integrates the AI Roadmap Coach header message generated by Kimi3.

import 'package:flutter/material.dart';
import 'package:signals_flutter/signals_flutter.dart';

import '../../state/auth_state.dart';
import '../../state/roadmap_actions.dart';
import '../../state/roadmap_state.dart';
import '../../state/ai_state.dart';
import '../../utils/app_colors.dart';
import '../../utils/constants.dart';
import '../../utils/onboarding_labels.dart';
import '../atoms/app_progress_bar.dart';
import '../organisms/roadmap_tree.dart';

class RoadmapPage extends StatelessWidget {
  const RoadmapPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SignalBuilder(
      builder: (context) {
        // Lazy load the first time it is painted. It is not called plainly in
        // the builder: that would fire a load on every rebuild.
        if (!roadmapLoaded.value &&
            !roadmapLoading.value &&
            roadmapError.value == null) {
          // Outside of the current build cycle, so signals do not change while
          // it is being built.
          WidgetsBinding.instance.addPostFrameCallback((_) => loadRoadmap());
        }

        final currentTrackName =
            trackName(currentProfile.value?.track) ?? 'your specialty';

        return SingleChildScrollView(
          padding: const EdgeInsets.symmetric(
            vertical: AppConstants.spacingLg,
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const _Header(),
              const SizedBox(height: AppConstants.spacingLg),
              if (roadmapLoading.value)
                const Center(
                  child: Padding(
                    padding: EdgeInsets.all(AppConstants.spacingXl),
                    child: CircularProgressIndicator(),
                  ),
                )
              else if (roadmapError.value != null)
                RoadmapErrorState(
                  message: roadmapError.value!,
                  onRetry: retryRoadmap,
                )
              else if (roadmapIsEmpty.value)
                RoadmapEmptyState(trackName: currentTrackName)
              else
                RoadmapTree(roots: roadmapTree.value),
            ],
          ),
        );
      },
    );
  }
}

/// Title, track, AI coaching message, and progress percentage.
class _Header extends StatelessWidget {
  const _Header();

  @override
  Widget build(BuildContext context) {
    return SignalBuilder(
      builder: (context) {
        final textTheme = Theme.of(context).textTheme;
        final total = roadmapLeaves.value.length;
        final completed = roadmapCompletedCount.value;
        final percentage = (roadmapProgress.value * 100).round();
        final currentTrackName =
            trackName(currentProfile.value?.track) ?? 'your specialty';

        return Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Row(
              children: [
                if (roadmapCoachMessage.value != null) ...[
                  const Icon(Icons.auto_awesome, size: 14, color: AppColors.primary),
                  const SizedBox(width: 4),
                ],
                Expanded(
                  child: Text(
                    (roadmapCoachMessage.value ?? 'Your path').toUpperCase(),
                    style: textTheme.labelMedium?.copyWith(
                      color: AppColors.primary,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 1.1,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: AppConstants.spacingXs),
            Text(currentTrackName, style: textTheme.headlineMedium),
            const SizedBox(height: AppConstants.spacingMd),
            // With no topics it does not show a 0% that would look like a failure:
            // there is nothing to measure against yet.
            if (total > 0) ...[
              AppProgressBar(
                value: roadmapProgress.value,
                semanticsLabel: 'Progress of your path',
              ),
              const SizedBox(height: AppConstants.spacingSm),
              Text(
                '$percentage% complete · $completed of $total topics',
                style: textTheme.bodyMedium?.copyWith(
                  color: AppColors.onSurfaceVariant,
                ),
              ),
            ],
          ],
        );
      },
    );
  }
}
