// Domain layer: Pure business entity (pure Dart, no Flutter, no JSON).
//
// One question generated by Kimi3 for an interview-practice session.
// Instances are created fresh per session (see
// InterviewRepository.generateQuestions): nothing here is persisted, so `id`
// only needs to be unique within a single session's lifetime, not globally.

class InterviewQuestion {
  const InterviewQuestion({
    required this.id,
    required this.prompt,
    required this.category,
  });

  /// Unique within the current session. Used to key answers/feedback by
  /// question without relying on list position.
  final String id;

  /// The question text, already in plain, beginner-friendly language.
  final String prompt;

  /// E.g. 'behavioral' or 'technical'. Purely descriptive: drives no logic
  /// today, but lets the UI show a small tag per question.
  final String category;
}
