// Domain layer: Pure business entity (pure Dart, no Flutter, no JSON).
//
// Output of `RecommendTrackUseCase`. It is a suggestion, not an assignment:
// issue #12 requires the user to confirm the result and be able to correct it
// by hand before it is persisted.
//
// AI-First: `reasoning` and `confidence` are populated when the recommendation
// comes from Kimi3 (via `AiRepository.analyzeProfile`). They are `null` when
// the fallback vote-count rule is used (e.g. offline or AI unavailable).

import 'roadmap_track.dart';

class TrackRecommendation {
  const TrackRecommendation({
    required this.track,
    required this.scores,
    required this.wasTie,
    this.reasoning,
    this.confidence,
    this.alternatives = const [],
  });

  /// With no usable answers there is nothing to recommend.
  const TrackRecommendation.empty()
      : track = null,
        scores = const <RoadmapTrack, int>{
          RoadmapTrack.frontend: 0,
          RoadmapTrack.backend: 0,
          RoadmapTrack.infrastructure: 0,
        },
        wasTie = false,
        reasoning = null,
        confidence = null,
        alternatives = const [];

  /// Suggested track, or `null` if there was no usable answer.
  final RoadmapTrack? track;

  /// Votes per track, including the ones that scored zero.
  ///
  /// For AI recommendations this map contains the confidence as a percentage
  /// of the recommended track, with 0 for the others. The UI should prefer
  /// [reasoning] when available.
  final Map<RoadmapTrack, int> scores;

  /// The highest score was shared by two or more tracks and [track] came out
  /// of a tie-break. The UI should say so instead of presenting the result as
  /// conclusive.
  final bool wasTie;

  // ---------------------------------------------------------------------------
  // AI-First fields (null when falling back to the vote-count rule)
  // ---------------------------------------------------------------------------

  /// Natural-language explanation of why Kimi3 chose this track for the user.
  ///
  /// Example: "Based on your interest in building visual interfaces and your
  /// goal of landing a first job, Frontend is your strongest starting point."
  final String? reasoning;

  /// How confident the AI is in its recommendation (0.0–1.0).
  ///
  /// Values below 0.85 trigger `wasTie = true` and surface [alternatives].
  final double? confidence;

  /// Alternative tracks suggested when [confidence] < 0.85.
  final List<TrackAlternative> alternatives;

  /// Whether this recommendation was generated by AI (has reasoning).
  bool get isAiGenerated => reasoning != null;

  bool get hasRecommendation => track != null;
}

/// An alternative track suggested by the AI when confidence is not high.
class TrackAlternative {
  const TrackAlternative({required this.track, required this.reason});

  final RoadmapTrack track;

  /// One-sentence explanation of why this track could also work.
  final String reason;
}
